import {Wish, Status} from './wish';


export const WISHES: Wish[] = [
  { name: 'Grille-pain', status: Status.MISSING },
  { name: 'Services en métal', status: Status.MISSING },
  { name: 'Couteaux', status: Status.MISSING },
  { name: 'Lampes de plafond', status: Status.MISSING },
  { name: 'Miroir pour salle de bain', status: Status.MISSING },
  { name: 'Double mètre', status: Status.MISSING },
  { name: 'Tringle et rideau de douche', status: Status.MISSING },
  { name: 'Linges de cuisine', status: Status.MISSING },
  { name: 'Multiprises', status: Status.MISSING },
  { name: 'Poney', status: Status.MISSING },
  { name: 'Patte à récurer', status: Status.MISSING },
  { name: 'Patte à poussière', status: Status.MISSING },
  { name: 'Langue de chat (cuisine)', status: Status.MISSING },
  { name: 'Boîte à pain', status: Status.MISSING },
  { name: 'Verres à eau', status: Status.MISSING },
  { name: 'Verres à vin', status: Status.MISSING },
  { name: 'Verres à bière', status: Status.MISSING },
  { name: 'Tasses à thé', status: Status.MISSING },
  { name: 'Tableau blanc ou noir', status: Status.MISSING },
  { name: 'Colocatair·ice', status: Status.MISSING },
  { name: 'Petit aspirateur à main', status: Status.MISSING },
  { name: 'Boîte à fromage', status: Status.MISSING },
  { name: 'Énorme clef à molette (5cm)', status: Status.MISSING },
  { name: 'Passoire', status: Status.MISSING },
  { name: 'Saladiers ou grands bols', status: Status.MISSING },
  { name: 'Poubelle pour sous l\'evier', status: Status.MISSING },
  { name: 'Poubelles de chambre', status: Status.MISSING },
  { name: 'Essoreuse à salade', status: Status.MISSING },
  { name: 'Chauffe-eau', status: Status.MISSING },
  { name: 'Planches à découper', status: Status.MISSING },
  { name: 'Brosse et ramassoire', status: Status.MISSING },
  { name: 'Tupperwares hermethique', status: Status.MISSING },
  { name: 'Petite tronçonneuse d\'élagage', status: Status.MISSING },
  { name: 'Poêle à crêpes', status: Status.MISSING },
  { name: 'Mortier en pierre', status: Status.MISSING },
  { name: 'Grand plat à gratin', status: Status.MISSING },
  { name: 'Râpe à légume', status: Status.MISSING },
  { name: 'Cintres pour vestes', status: Status.MISSING },

];
